import assert from "node:assert/strict";
import test from "node:test";
import {
  createCandidateLedger,
  publicDiscoveryStats,
  setCandidateDecision,
  summarizeCandidateLedger,
  validateCandidateLedger,
} from "../lib/candidate-ledger.js";

const discoveries = [
  { discoveryId: "feed:a", url: "https://example.com/a", origin: { kind: "rss" } },
  { discoveryId: "github:acme/old", url: "https://github.com/acme/old", origin: { kind: "github-trending" } },
];

test("a completed ledger reconciles every eligible item and Trending rejection", () => {
  let ledger = createCandidateLedger({ editionDate: "2026-08-20", discoveries, failures: [] });
  ledger = setCandidateDecision(ledger, "feed:a", { status: "eligible", itemId: "item-a", rationale: "Current release." });
  ledger.candidates[0].copy = {
    promptVersion: "broad-tech-copy-v2",
    evidenceFacts: ["Acme released Trace Viewer for local browser debugging."],
    title: "Acme releases Trace Viewer",
    summary: "The local tool records browser network and rendering traces in one file.",
  };
  ledger = setCandidateDecision(ledger, "github:acme/old", { status: "rejected", reason: "inactive", rationale: "No activity in twelve months." });
  assert.deepEqual(validateCandidateLedger(ledger, {
    date: "2026-08-20",
    items: [{
      id: "item-a",
      title: "Acme releases Trace Viewer",
      summary: "The local tool records browser network and rendering traces in one file.",
    }],
  }), []);
  assert.deepEqual(summarizeCandidateLedger(ledger), {
    rawCandidates: 2,
    clusteredCandidates: 2,
    eligibleCandidates: 1,
    rejectedCandidates: 1,
    pendingCandidates: 0,
    trendingReviewed: 1,
    feedFailures: 0,
  });
  assert.deepEqual(publicDiscoveryStats(ledger, { publishedItems: 1, explorationItems: 0 }), {
    rawCandidates: 2,
    clusteredCandidates: 2,
    eligibleCandidates: 1,
    publishedItems: 1,
    trendingReviewed: 1,
    explorationItems: 0,
  });
});

test("ledger validation rejects copy generated by an obsolete prompt", () => {
  let ledger = createCandidateLedger({ editionDate: "2026-08-20", discoveries: [discoveries[0]], failures: [] });
  ledger = setCandidateDecision(ledger, "feed:a", { status: "eligible", itemId: "item-a", rationale: "Current release." });
  ledger.candidates[0].copy = {
    promptVersion: "broad-tech-baseline-v1",
    evidenceFacts: ["Acme released Trace Viewer."],
    title: "Acme releases Trace Viewer",
    summary: "The tool records browser traces locally.",
  };

  assert.match(validateCandidateLedger(ledger).join("\n"), /broad-tech-copy-v2/);
});

test("ledger validation rejects generic AI phrasing and decorative headline verbs", () => {
  let ledger = createCandidateLedger({ editionDate: "2026-08-20", discoveries: [discoveries[0]], failures: [] });
  ledger = setCandidateDecision(ledger, "feed:a", { status: "eligible", itemId: "item-a", rationale: "Current release." });
  ledger.candidates[0].copy = {
    promptVersion: "broad-tech-copy-v2",
    evidenceFacts: ["Acme added Trace Viewer to its browser tools."],
    title: "Trace Viewer lands with a groundbreaking workflow",
    summary: "This pivotal release unlocks a seamless debugging experience in today's evolving developer landscape.",
  };

  const errors = validateCandidateLedger(ledger).join("\n");
  assert.match(errors, /decorative headline verb/);
  assert.match(errors, /AI-default phrase/);
});

test("ledger validation rejects a summary that merely repeats its headline", () => {
  let ledger = createCandidateLedger({ editionDate: "2026-08-20", discoveries: [discoveries[0]], failures: [] });
  ledger = setCandidateDecision(ledger, "feed:a", { status: "eligible", itemId: "item-a", rationale: "Current release." });
  ledger.candidates[0].copy = {
    promptVersion: "broad-tech-copy-v2",
    evidenceFacts: ["Cloudflare added Qwen 3.8 27B to Workers AI."],
    title: "Cloudflare adds Qwen 3.8 27B to Workers AI",
    summary: "Cloudflare added Qwen 3.8 27B to Workers AI.",
  };

  assert.match(validateCandidateLedger(ledger).join("\n"), /repeats the title/);
});

test("discovery creates evidence-backed stale decisions outside each freshness class", () => {
  const ledger = createCandidateLedger({
    editionDate: "2026-08-20",
    discoveries: [
      { discoveryId: "release", url: "https://example.com/release", ageDays: 8, freshnessClass: "standard" },
      { discoveryId: "research", url: "https://example.com/research", ageDays: 8, freshnessClass: "extended" },
    ],
  });
  assert.equal(ledger.candidates[0].decision.reason, "stale");
  assert.equal(ledger.candidates[1].decision.status, "pending");
});

test("ledger validation rejects pending and unaccounted candidates", () => {
  const ledger = createCandidateLedger({ editionDate: "2026-08-20", discoveries, failures: [] });
  assert.equal(validateCandidateLedger(ledger).filter((error) => error.includes("pending")).length, 2);
});

test("canonical duplicates cluster before editorial decisions", () => {
  const ledger = createCandidateLedger({
    editionDate: "2026-08-20",
    discoveries: [
      { discoveryId: "one", url: "https://example.com/story?utm_source=a" },
      { discoveryId: "two", url: "https://example.com/story" },
    ],
  });
  assert.equal(new Set(ledger.candidates.map((item) => item.clusterId)).size, 1);
  assert.deepEqual(ledger.candidates[1].decision, { status: "rejected", reason: "clustered", rationale: "Clustered with one." });
});
